---
title: "git_01"
author: "Math_116"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

’Twas brillig, and the slithy toves

  Did gyre and gimble in the wabe: 

All mimsy were the borogoves, 

  And the mome raths outgrabe. 

“Beware the Jabberwock, my son! 

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
All out of doors looked darkly in at him

Through the thin frost, almost in separate stars,

That gathers on the pane in empty rooms.

What kept his eyes from giving back the gaze

Was the lamp tilted near them in his hand.



## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

The sun was shining on the sea,

Shining with all his might:

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->

The rose is a rose,

And was always a rose.

But the theory now goes

That the apple’s a rose,

And the pear is, and so’s

The plum, I suppose.

The dear only knows

What will next prove a rose.

You, of course, are a rose –

But were always a rose.